// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import "./globals.css";
// import LanguageSwitcher from "./components/LanguageSwitcher";
// import { ReactNode } from "react";

// interface Props {
//   children: ReactNode;
//   params: { locale: string };
// }

// export const metadata = {
//   title: "Medical Center",
//   description: "Medical Center Website",
// };

// interface RootLayoutProps {
//   children: ReactNode;
//   params: { locale: string }; // Next.js يمرر الـ locale من المسار
// }


// export default function RootLayout({ children, params }: RootLayoutProps) {
//   const locale = params.locale === "ar" ? "ar" : "en";
//   const dir = locale === "ar" ? "rtl" : "ltr";


//   return (
//     <html lang={locale} dir={dir}>
//       <body className="min-h-screen flex flex-col">
//         <header className="p-4 border-b flex justify-between items-center">
//           <h1 className="text-xl font-bold">
//             {/* {locale === "en" ? "Medical Center" : "المركز الطبي"} */}
//             {locale === "ar" ?"المركز الطبي" : "Medical Center" }

//           </h1>
//           <LanguageSwitcher />
//         </header>

//         <main className="flex-1">{children}</main>

//         <footer className="p-4 border-t text-center">
//           {locale === "en"
//             ? "© 2026 Medical Center. All rights reserved."
//             : "© 2026 المركز الطبي. جميع الحقوق محفوظة."}
//         </footer>
//       </body>
//     </html>
//   );
// }
import "./globals.css";
import Navbar from "../components/Navbar";
import { ReactNode } from "react";
import { Locale } from "../lib/locale";

interface RootLayoutProps {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale: localeStr } = await params;
  const locale = (localeStr === "ar" ? "ar" : "en") as Locale;
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={dir}>
      <body className="min-h-screen flex flex-col">
        <Navbar currentLocale={locale} />

        <main className="flex-1">{children}</main>

        <footer className="p-4 border-t text-center">
          {locale === "en"
            ? "© 2026 Medical Center. All rights reserved."
            : "© 2026 المركز الطبي. جميع الحقوق محفوظة."}
        </footer>
      </body>
    </html>
  );
}
